server {
    listen 8080;
    server_name _;

    client_max_body_size 2m;

    location = /health {
        access_log off;
        proxy_pass http://postgrest:3001/ready;
    }

    location = /rest/v1 {
        proxy_pass http://postgrest:3000/;
        proxy_set_header Authorization $http_authorization;
        proxy_set_header Accept-Profile $http_accept_profile;
        proxy_set_header Content-Profile $http_content_profile;
        proxy_set_header Prefer $http_prefer;
    }

    location /rest/v1/ {
        proxy_pass http://postgrest:3000/;
        proxy_http_version 1.1;
        proxy_set_header Authorization $http_authorization;
        proxy_set_header Accept-Profile $http_accept_profile;
        proxy_set_header Content-Profile $http_content_profile;
        proxy_set_header Prefer $http_prefer;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        return 404;
    }
}
